apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-wk-2
  labels:
    type: local
spec:
  storageClassName: standard-local-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: gitlab-runner
    name: minio-pv-claim-2
  local:
    path: /apps/k8s/gitlab-runner/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim-2
  namespace: gitlab-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
