apiVersion: v1
kind: Service
metadata:
  name: minio-service-ext
  namespace: gitlab-runner
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
